# src/game/constants.py

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 600
BIG_CARD_WIDTH = 48
BIG_CARD_HEIGHT = 64
MINI_CARD_WIDTH = 15
MINI_CARD_HEIGHT = 22
BIG_SCALE_FACTOR = 3
MINI_SCALE_FACTOR = 6
CARD_SPACING = 10
MAX_HAND_LIMIT = 5
FPS = 60
